### ISSUE TITLE
enable_proof_check in a text_ctrl on Windows 11 doesn't do anything

### ISSUE THREAD

**Issue by Randalphwa** [mcorino/wxRuby3#142]
I created a text control with the following code:

```Ruby
    @text_ctrl = Wx::TextCtrl.new(self, Wx::ID_ANY, '', Wx::DEFAULT_POSITION,
      Wx::DEFAULT_SIZE, Wx::TE_RICH2)
    @text_ctrl.enable_proof_check(Wx::TextProofOptions.default)
```

There are no complaints from Ruby, but when I enter in "tast" and a space, no spell checking is done.

By contrast, if I create the following C++ code:

```C++
    text_ctrl = new wxTextCtrl(this, wxID_ANY, wxEmptyString,
        wxDefaultPosition, wxDefaultSize, wxTE_RICH2);
    text_ctrl->EnableProofCheck(wxTextProofOptions::Default());
```

This works as expected -- I get the red squiqly underline under "tast" when I press space after entering in the misspelled word.

This is running on Windows 11.

**Comment by Randalphwa** [comment]
I should also mention that while not documented, `grammar_check` appears to exist, or at least I can call it without any complaints from Ruby `@textCtrl.enable_proof_check(Wx::TextProofOptions.default.grammar_check)`. However, like `enable_proof_check` it doesn't seem to have any effect (but does in equivalent C++ code).

**Comment by mcorino** [comment]
I am somewhat surprised you report no errors as it turned out the methods and class TextProofOptions were not wrapped AT ALL yet.
But no matter, they have been added now  on the master branch through PR #152.

Things to notice though:

- the only thing supported on all platforms (WXMSW, WXGTK and WXOSX) is spell checking;
- the WXMSW implementation incorrectly returns false when disabling spell checking for wxWidgets < 3.3 (I submitted a PR for 3.3+);
- no platform currently supports setting the language through Wx::TextProofOptions (the `language` setting is a dud);
- **ONLY** WXOSX currently supports grammar checking

You say enabling grammar check had an effect so you either were working on OSX or you noticed an other effect ;-)
