### ISSUE TITLE
wxWrapSizer not implemented

### ISSUE THREAD

**Issue by Randalphwa** [mcorino/wxRuby3#148]
I'm not sure if this is by design or an oversight, but `wxWrapSizer` is not implemented. This is a more significant problem for wxUiEditor than the handful of other controls that wxUE supports but wxRuby3 does not. In this case, the user can create multiple children under the sizer, but wxUE cannot generate working Ruby code unless I change the wxWrapSizer they specified into a box sizer which of course won't work the way the user would expect. If it's by design, I'll go ahead and write the generating code to work around it -- but I didn't want to do that unless I knew for sure this wouldn't be in the wxRuby3 1.0 release.

**Comment by mcorino** [comment]
Definitely not by design. wxWidgets is however such an extensive library that I expect this not to be the last widget/class that I find to be missed out of wrapping.On Aug 23, 2023 14:37, Randalphwa ***@***.***> wrote:
I'm not sure if this is by design or an oversight, but wxWrapSizer is not implemented. This is a more significant problem for wxUiEditor than the handful of other controls that wxUE supports but wxRuby3 does not. In this case, the user can create multiple children under the sizer, but wxUE cannot generate working Ruby code unless I change the wxWrapSizer they specified into a box sizer which of course won't work the way the user would expect. If it's by design, I'll go ahead and write the generating code to work around it -- but I didn't want to do that unless I knew for sure this wouldn't be in the wxRuby3 1.0 release.
