### ISSUE TITLE
Feature request: additional constructor for Wx::StaticBoxSizer

### ISSUE THREAD

**Issue by Randalphwa** [mcorino/wxRuby3#201]
The wxRuby3 documentation for `Wx::StaticBox` shows a variation of initialize that allows passing in a `Wx::Window` instead of a String for the label parameter. However, Wx::StaticBoxSizer does not have the alternate constructor. When I try the following code in order to get a checkbox as the label for a static box:

```Ruby
    checkPlayAnimation = Wx::CheckBox.new(self, Wx::ID_ANY, 'Play Animation')
    static_box_3 = Wx::StaticBoxSizer.new(Wx::VERTICAL, self, checkPlayAnimation)
```

I get:

```
`initialize': Wrong arguments for overloaded method 'wxStaticBoxSizer.new'. (ArgumentError)
```

My question is, since the underlying `Wx::StaticBox` already supports a `Wx::Window` as the label, would it be possible to add another constructor to `Wx::StaticBoxSizer` which also used a `Wx::Window` as the third parameter?

**Comment by mcorino** [comment]
This is a feature request you would first have to submit to the wxWidgets project since the C++ implementation of wxStaticBoxSizer currently does not support this ctor.
wxRuby in principle only supports what the wxWidgets API offers by default.
The wxRuby project is not intended to provide extensions to the wxWidgets API (except for some minor convenience items). That would be the purpose of add-on libraries like https://github.com/mcorino/wxRuby3-shapes.
