### ISSUE TITLE
Possible missing constant: Wx::FileSelectorPromptStr

### ISSUE THREAD

**Issue by Randalphwa** [mcorino/wxRuby3#203]
Following the documentation (https://mcorino.github.io/wxRuby3/Wx/FilePickerCtrl.html) for the default message parameter, I tried creating the following:

```ruby
    @filePicker = Wx::FilePickerCtrl.new(static_box_2.get_static_box, Wx::ID_ANY, (''),
      Wx::FileSelectorPromptStr, 'BMP files|*.bmp', Wx::DEFAULT_POSITION,
      Wx::DEFAULT_SIZE, Wx::FLP_USE_TEXTCTRL|Wx::FLP_OPEN|Wx::FLP_FILE_MUST_EXIST)
```

I then get:

```
global_const.rb:50:in `const_missing': uninitialized constant Wx::FileSelectorPromptStr (NameError)
```

I did try the uppercase snake-case version of the constant (`Wx::FILE_SELECTOR_PROPT_STR`), but that didn't work either.

**Comment by mcorino** [comment]
The problem with constants like this one is that they are referenced in the documentation (as argument defaults) but not **documented** themselves. It is therefor not possible for the build scripts to generate wrapping code for them.
Manually wrapping would require trawling through the documentation looking for these and than checking the wxWidgets C++ code to find out what value the constant has.
That is not something I ever intend to do structurally.
The argument default as documented will still work (because that's coded in C++) but directly referencing them will cause errors like this.
Fixing them when found is not that difficult by just adding a constant definition in pure Ruby in an appropriate file in the Ruby code part of the wxRuby library.
I will pick this one up still and add a patch to the library but for future issues like this I will suggest users themselves submit PR's with the appropriate patch.

**Comment by mcorino** [comment]
BTW, this report did point out to me that constant naming was not fully consistent in wxRuby (particularly concerning these "referenced but not officially documented" constants).
Thanks for that. 
I fixed that now and added Wx::FILE_SELECTOR_PROMPT_STR to the library.

For future reference: any missing constants like this should be added to `lib/wx/core/const.rb` with an additional entry in `lib/wx/doc/const.rb` to enable documentation crossreferences (unlike in wxWidgets docs).
